const dataprod = [
    {
    id: 1,    
    name: 'Diferentes papeles',
    image: '/uploads/image-1636923549596.jpg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Papeleria',
    category: 'Papeleria',
    price: 99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 6,
    },
    {
    id: 2,
    name: 'El peor café del mundo!',
    image: '/uploads/image-1636923695911.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Comida',
    category: 'Comida',
    price: 29,
    countInStock: 15,
    rating: 4.0,
    numReviews: 8,
    },
    {
    id: 3,
    name: 'Pedazos de madera',
    image: '/uploads/image-1636923770106.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Juegos',
    category: 'Juegos',
    price: 50,
    countInStock: 20,
    rating: 3,
    numReviews: 4,
    },
    {
    id: 4,    
    name: 'Tarjetas de presentación',
    image: '/uploads/image-1636923826799.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Papeleria',
    category: 'Papeleria',
    price: 35,
    countInStock: 20,
    rating: 5,
    numReviews: 9,
    },
    {
    id: 6,    
    name: 'iPad Cover',
    image: '/uploads/image-1636923883495.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Accesorios',
    category: 'Accesorios',
    price: 399,
    countInStock: 12,
    rating: 3.5,
    numReviews: 10,
    },
    {
    id: 7,        
    name: 'Tarjetas de presentación',
    image: '/uploads/image-1636923946729.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Papeleria',
    category: 'Papeleria',
    price: 287,
    countInStock: 10,
    rating: 4,
    numReviews: 0,
    },
    {
    id: 8,    
    name: 'Bolsas con diseños',
    image: '/uploads/image-1636924007021.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Accesorios',
    category: 'Accesorios',
    price: 220,
    countInStock: 35,
    rating: 4,
    numReviews: 2,
    },
    {
    id: 9,
    name: 'Diseño de Apps',
    image: '/uploads/image-1636924055927.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Tecnologia',
    category: 'Tecnologia',
    price: 650,
    countInStock: 10,
    rating: 4,
    numReviews: 7,
    },
    {
    id: 10,
    name: 'Libro con muchas letras',
    image: '/uploads/image-1636924125871.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Libros',
    category: 'Libros',
    price: 499,
    countInStock: 50,
    rating: 4,
    numReviews: 4,
    },
    {
    id: 11,    
    name: 'Camisetas con diseños',
    image: '/uploads/image-1636924177344.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Ropa',
    category: 'Ropa',
    price: 237,
    countInStock: 10,
    rating: 4,
    numReviews: 6,
    },
    {
    id: 12,
    name: 'Lapiceros',
    image: '/uploads/image-1636924237616.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Accesorios',
    category: 'Accesorios',
    price: 385,
    countInStock: 10,
    rating: 3.5,
    numReviews: 6,
    },
    {
    id: 13,    
    name: 'Hojas con manchas',
    image: '/uploads/image-1636924296650.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Libros',
    category: 'Libros',
    price: 237,
    countInStock: 11,
    rating: 3,
    numReviews: 5,
    },
    {
    id: 14,
    name: 'Papeles sucios',
    image: '/uploads/image-1636924339177.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Papeleria',
    category: 'Papeleria',
    price: 99,
    countInStock: 30,
    rating: 4.5,
    numReviews: 9,
    },
    {
    id: 15,
    name: 'Camisetas usadas',
    image: '/uploads/image-1636924378927.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Ropa',
    category: 'Ropa',
    price: 53,
    countInStock: 10,
    rating: 4,
    numReviews: 3,
    },
    {
    id: 16,
    name: 'Todos necesitan ropa',
    image: '/uploads/image-1636924475351.jpeg',
    description:
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    brand: 'Ropa',
    category: 'Ropa',
    price: 20,
    countInStock: 20,
    rating: 4,
    numReviews: 1,
    },
    {
    id: 17,    
    name: 'Diseño de bolsa',
    image: '/uploads/image-1636924538034.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Bolsas',
    category: 'Bolsas',
    price: 48,
    countInStock: 25,
    rating: 4,
    numReviews: 3,
    },
    {
    id: 18,
    name: 'Aquí los cortamos para ti',
    image: '/uploads/image-1636924603411.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Madera',
    category: 'Madera',
    price: 549,
    countInStock: 6,
    rating: 3.5,
    numReviews: 5,
    },
    {
    id: 19,
    name: 'Cajas para cosas',
    image: '/uploads/image-1636924675397.jpeg',
    description:
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    brand: 'Cajas',
    category: 'Cajas',
    price: 825,
    countInStock: 8,
    rating: 4.5,
    numReviews: 6,
    },
];
module.exports = dataprod;


  
